# Use the official NVIDIA CUDA 10.1 image as the base image
FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git nano\                     
    libeigen3-dev libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev \                      
    libavutil-dev libswresample-dev libsamplerate0-dev libtag1-dev libchromaprint-dev \
    python3-pip \                  
    python3-dev python3-numpy-dev python3-numpy python3-yaml python3-six \                         
&& rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install tensorflow-gpu==2.2.0

ENV LANG=C.UTF-8

RUN git clone --recursive https://github.com/MTG/essentia.git /opt/essentia

## build
WORKDIR /opt/essentia
RUN python3 waf --help
RUN python3 -c "import sys;print(sys.path)"
RUN nohup sh src/3rdparty/tensorflow/setup_from_python.sh > /opt/essentia/fromnvidia_cmdwafsg.out
RUN nohup python3 waf configure --with-tensorflow --with-python --with-examples --pythondir=/usr/local/lib/python3.6/dist-packages > /opt/essentia/fromnvidia_cmdwafconfig.out 
RUN python3 waf -v

#RUN python3 waf install && \
#    ldconfig && \
#    python3 waf run_python_tests

