alias c='clear'
alias e='exit'
alias catghpw='cat /raid/DATASETS/.zuble/.g'
alias cdvigia='cd /raid/DATASETS/.zuble/vigia'
alias condazhengpu='conda activate zhen_gpu'
alias condazugpu='conda activate zugpu'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias nvidia='watch -n 0.5 nvidia-smi'