## sucess running zurgb11/train.py

FROM tensorflow/tensorflow:2.2.0-gpu

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt-get update

RUN pip install --upgrade pip
#RUN pip install --upgrade pip setuptools wheel


############### 1 #################
RUN pip install --no-cache-dir \
    opencv-python-headless==4.5.3.56 \
    moviepy \
    scikit-learn \
    seaborn \
    tqdm

###################################
RUN python -c "import numpy; print('NumPy version:', numpy.__version__)"


# Set working directory
WORKDIR /home/vigia/zurgb11

# Set the default command to run when the container starts
CMD ["/bin/bash"]