## 

FROM tensorflow/tensorflow:2.2.0-gpu
RUN python --version

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        nano && \
    rm -rf /var/lib/apt/lists/*


############### RGB #################
RUN pip install --upgrade pip

# moviepy is actualy for wav
RUN pip install --no-cache-dir \
    opencv-python-headless==4.5.3.56 \
    moviepy \
    scikit-learn \
    seaborn \
    tqdm

RUN python -c "import numpy; print('NumPy version:', numpy.__version__)"


############### WAV #################

## dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential libeigen3-dev libyaml-dev \
        libfftw3-dev libavcodec-dev libavformat-dev \
        libavutil-dev libswresample-dev libsamplerate0-dev \
        libtag1-dev libchromaprint-dev && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \        
        python3-dev python3-numpy-dev python3-numpy \
        python3-yaml python3-six && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/MTG/essentia.git /opt/essentia

## build
WORKDIR /opt/essentia
RUN python3 waf --help
RUN python3 -c "import sys;print(sys.path)"
RUN nohup sh src/3rdparty/tensorflow/setup_from_python.sh > /opt/essentia/fromtf220_cmdwafsg.out
RUN nohup python3 waf configure --with-tensorflow --with-python --with-examples --pythondir=/usr/local/lib/python3.6/dist-packages > /opt/essentia/fromtf220_cmdwafconfig.out 
RUN python3 waf -v

#RUN python3 waf install && \
#    ldconfig && \
#    python3 waf run_python_tests

#rm -rf /opt/essentia/.git    
#RUN apt-get remove -y build-essential libyaml-dev libfftw3-dev libavcodec-dev libavformat-dev libavutil-dev libavresample-dev python-dev libsamplerate0-dev libtag1-dev && \
#    apt-get autoremove -y && apt-get clean -y && \
#    rm -rf /var/lib/apt/lists/* && cd / && rm -rf /essentia/essentia


###################################

# Set working directory
WORKDIR /home/vigia

# Set the default command to run when the container starts
CMD ["/bin/bash"]